language: ruby
cache: bundler
script: 'bundle exec rake'
sudo: required
dist: trusty
rvm:
  - 2.7.2

notifications:
  email:
    recipients:
      - a@asgerbehnckejacobsen.dk
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
